data = [
    {
        "name": "Instagram",
        "follower_count": 670,
        "description": "Social media platform",
        "country": "United States",
    },
    {
        "name": "Cristiano Ronaldo",
        "follower_count": 620,
        "description": "Footballer",
        "country": "Portugal",
    },
    {
        "name": "Lionel Messi",
        "follower_count": 500,
        "description": "Footballer",
        "country": "Argentina",
    },
    {
        "name": "Selena Gomez",
        "follower_count": 430,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Kylie Jenner",
        "follower_count": 400,
        "description": "Reality TV star and businesswoman",
        "country": "United States",
    },
    {
        "name": "Dwayne Johnson",
        "follower_count": 395,
        "description": "Actor and professional wrestler",
        "country": "United States",
    },
    {
        "name": "Ariana Grande",
        "follower_count": 380,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Kim Kardashian",
        "follower_count": 364,
        "description": "Reality TV star and businesswoman",
        "country": "United States",
    },
    {
        "name": "Beyoncé",
        "follower_count": 315,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Justin Bieber",
        "follower_count": 293,
        "description": "Musician",
        "country": "Canada",
    },
    {
        "name": "Taylor Swift",
        "follower_count": 280,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "National Geographic",
        "follower_count": 282,
        "description": "Magazine",
        "country": "United States",
    },
    {
        "name": "Nike",
        "follower_count": 306,
        "description": "Sportswear multinational",
        "country": "United States",
    },
    {
        "name": "Neymar",
        "follower_count": 219,
        "description": "Footballer",
        "country": "Brazil",
    },
    {
        "name": "Nicki Minaj",
        "follower_count": 229,
        "description": "Musician",
        "country": "Trinidad and Tobago",
    },
    {
        "name": "Miley Cyrus",
        "follower_count": 216,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "Katy Perry",
        "follower_count": 206,
        "description": "Musician",
        "country": "United States",
    },
    {
        "name": "Zendaya",
        "follower_count": 184,
        "description": "Actress and musician",
        "country": "United States",
    },
    {
        "name": "Kevin Hart",
        "follower_count": 179,
        "description": "Comedian and actor",
        "country": "United States",
    },
    {
        "name": "Real Madrid CF",
        "follower_count": 155,
        "description": "Football club",
        "country": "Spain",
    },
    {
        "name": "FC Barcelona",
        "follower_count": 126,
        "description": "Football club",
        "country": "Spain",
    },
    {
        "name": "Rihanna",
        "follower_count": 152,
        "description": "Musician and businesswoman",
        "country": "Barbados",
    },
    {
        "name": "LeBron James",
        "follower_count": 159,
        "description": "Basketball player",
        "country": "United States",
    },
    {
        "name": "Demi Lovato",
        "follower_count": 157,
        "description": "Musician and actress",
        "country": "United States",
    },
    {
        "name": "NASA",
        "follower_count": 97,
        "description": "Space agency",
        "country": "United States",
    },
]
